from decimal import Decimal

from pydantic import BaseModel, ConfigDict, Field

from app.models.enums import EquipmentStatus


# Define core fields and validation (Base Model for Equipment class)
class EquipmentBase(BaseModel):
    # id: int
    # serial_number: string(50)
    # model: string(100)
    # status: enum(EquipmentStatus)
    # fuel_level: numeric(0-100)
    # farm_id: int (foreign key, farm)

    # note: id autogenerated by db
    serial_number: str = Field(min_length=1, max_length=50) # Pydantic would autoreject strings outside constraints)
    model: str = Field(min_length=1, max_length=100)
    status: EquipmentStatus = EquipmentStatus.IDLE
    fuel_level: Decimal = Field(ge=0, le=100) # greater than or equal to, less than or equal to
    farm_id: int

class EquipmentCreate(EquipmentBase):
    pass # Would inherit every field/constraint from the EquipmentBase

class EquipmentRead(EquipmentBase):
    id: int
    model_config = ConfigDict(from_attributes=True)

# Typical Classes in Schema Files:
# ModelBase
# ModelCreate
# ModelRead
# ModelUpdate
# ModelDelete

# Note: It seems any creation into the database doesn't require the id, just the info
# But if you're doing anything that requires the id (reading, updating), perhaps include it?
# Eg. Incoming CREATE Request: no id required, will be generated by the db
# EquipmentCreate validates input
# EquipmentRead, reads attributes from ORM, include id into json output

# Guess: Okay no, I'm realizing this is literally just the API schema.
# Like the format that the router expects before performing any code.
# Surely, this must differ from the format sent back in the response body.
# But maybe you can use these schemas as formats to both RECEIVE AND RESPOND?

# Request bodies are validated by pydantic before code ever runs.

# Note: model_config = ConfigDict(from_attributes=True)
# This line is needed for any schema where you grab something from the database
# because the code cannot read it without it. Then it'll automatically grab whatever
# attributes it can find that was defined in your base model. Oftentimes you may need
# to add id: because it's not in your base model, usually.
# You don't need it for Create/Update, only Read/Response