from decimal import Decimal
from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict, Field

from app.models.enums import EquipmentStatus

class ServiceReportBase(BaseModel):
    # id: Mapped[int] = mapped_column(primary_key=True)
    # field_job_id: Mapped[int] = mapped_column(Integer, ForeignKey("field_jobs.id"))
    # file_url: Mapped[str] = mapped_column(Text)
    # notes: Mapped[str | None] = mapped_column(Text, nullable=True)
    # timestamp: Mapped[datetime] = mapped_column(DateTime, default=func.now())

    # note: id autogenerated by db
    field_job_id: int
    file_url: str
    notes: str | None = None

class ServiceReportCreate(ServiceReportBase):
    pass 

class ServiceReportRead(ServiceReportBase):
    id: int
    timestamp: datetime
    model_config = ConfigDict(from_attributes=True)


class ServiceReportUpdate(BaseModel): # Only allowing change of notes.
    notes: Optional[str] = None